@startuml

Client1 -> Serveur: Authentification
Serveur -> Client1: OK
Client2 -> Serveur: Authentification
Serveur -> Client2: OK
loop communication
Client1 -> Serveur: Envoi d'un message
Serveur -> Client2: Relai du message (thread1)
Client2 -> Serveur: Message reçu
Client2 -> Serveur: Envoi d'un message
Serveur -> Client1: Relai du message (thread2)
Client1 -> Serveur: Message reçu
alt message "fin"
    Serveur -> Client1: arrêt communication
    Serveur -> Client2: arrêt communication
end
end
@enduml
